export const countries = [
    { country: "Afghanistan", country_ar: "أفغانستان" },
    { country: "Albania", country_ar: "ألبانيا" },
    { country: "Algeria", country_ar: "الجزائر" },
    { country: "Andorra", country_ar: "أندورا" },
    { country: "Angola", country_ar: "أنغولا" },
    { country: "Argentina", country_ar: "الأرجنتين" },
    { country: "Armenia", country_ar: "أرمينيا" },
    { country: "Australia", country_ar: "أستراليا" },
    { country: "Austria", country_ar: "النمسا" },
    { country: "Azerbaijan", country_ar: "أذربيجان" },
    { country: "Bahrain", country_ar: "البحرين" },
    { country: "Bangladesh", country_ar: "بنغلاديش" },
    { country: "Belarus", country_ar: "بيلاروس" },
    { country: "Belgium", country_ar: "بلجيكا" },
    { country: "Belize", country_ar: "بليز" },
    { country: "Benin", country_ar: "بنين" },
    { country: "Bhutan", country_ar: "بوتان" },
    { country: "Bosnia and Herzegovina", country_ar: "البوسنة والهرسك" },
    { country: "Botswana", country_ar: "بوتسوانا" },
    { country: "Brazil", country_ar: "البرازيل" },
    { country: "Brunei", country_ar: "بروناي" },
    { country: "Bulgaria", country_ar: "بلغاريا" },
    { country: "Burkina Faso", country_ar: "بوركينا فاسو" },
    { country: "Burundi", country_ar: "بوروندي" },
    { country: "Cameroon", country_ar: "الكاميرون" },
    { country: "Canada", country_ar: "كندا" },
    { country: "Chad", country_ar: "تشاد" },
    { country: "Chile", country_ar: "تشيلي" },
    { country: "China", country_ar: "الصين" },
    { country: "Colombia", country_ar: "كولومبيا" },
    { country: "Comoros", country_ar: "جزر القمر" },
    { country: "Congo (Brazzaville)", country_ar: "الكونغو - برازافيل" },
    { country: "Congo (Kinshasa)", country_ar: "الكونغو - كينشاسا" },
    { country: "Costa Rica", country_ar: "كوستاريكا" },
    { country: "Croatia", country_ar: "كرواتيا" },
    { country: "Cuba", country_ar: "كوبا" },
    { country: "Cyprus", country_ar: "قبرص" },
    { country: "Czechia", country_ar: "التشيك" },
    { country: "Denmark", country_ar: "الدانمارك" },
    { country: "Djibouti", country_ar: "جيبوتي" },
    { country: "Dominican Republic", country_ar: "جمهورية الدومينيكان" },
    { country: "Ecuador", country_ar: "الإكوادور" },
    { country: "Egypt", country_ar: "مصر" },
    { country: "El Salvador", country_ar: "السلفادور" },
    { country: "Estonia", country_ar: "إستونيا" },
    { country: "Eswatini", country_ar: "إسواتيني" },
    { country: "Ethiopia", country_ar: "إثيوبيا" },
    { country: "Fiji", country_ar: "فيجي" },
    { country: "Finland", country_ar: "فنلندا" },
    { country: "France", country_ar: "فرنسا" },
    { country: "Gabon", country_ar: "الغابون" },
    { country: "Gambia", country_ar: "غامبيا" },
    { country: "Georgia", country_ar: "جورجيا" },
    { country: "Germany", country_ar: "ألمانيا" },
    { country: "Ghana", country_ar: "غانا" },
    { country: "Greece", country_ar: "اليونان" },
    { country: "Guatemala", country_ar: "غواتيمالا" },
    { country: "Guinea", country_ar: "غينيا" },
    { country: "Guyana", country_ar: "غيانا" },
    { country: "Haiti", country_ar: "هايتي" },
    { country: "Honduras", country_ar: "هندوراس" },
    { country: "Hungary", country_ar: "المجر" },
    { country: "Iceland", country_ar: "آيسلندا" },
    { country: "India", country_ar: "الهند" },
    { country: "Indonesia", country_ar: "إندونيسيا" },
    { country: "Iran", country_ar: "إيران" },
    { country: "Iraq", country_ar: "العراق" },
    { country: "Ireland", country_ar: "أيرلندا" },
    { country: "Italy", country_ar: "إيطاليا" },
    { country: "Ivory Coast", country_ar: "ساحل العاج" },
    { country: "Jamaica", country_ar: "جامايكا" },
    { country: "Japan", country_ar: "اليابان" },
    { country: "Jordan", country_ar: "الأردن" },
    { country: "Kazakhstan", country_ar: "كازاخستان" },
    { country: "Kenya", country_ar: "كينيا" },
    { country: "Kuwait", country_ar: "الكويت" },
    { country: "Kyrgyzstan", country_ar: "قرغيزستان" },
    { country: "Laos", country_ar: "لاوس" },
    { country: "Latvia", country_ar: "لاتفيا" },
    { country: "Lebanon", country_ar: "لبنان" },
    { country: "Lesotho", country_ar: "ليسوتو" },
    { country: "Liberia", country_ar: "ليبيريا" },
    { country: "Libya", country_ar: "ليبيا" },
    { country: "Liechtenstein", country_ar: "ليختنشتاين" },
    { country: "Lithuania", country_ar: "ليتوانيا" },
    { country: "Luxembourg", country_ar: "لوكسمبورغ" },
    { country: "Madagascar", country_ar: "مدغشقر" },
    { country: "Malawi", country_ar: "مالاوي" },
    { country: "Malaysia", country_ar: "ماليزيا" },
    { country: "Maldives", country_ar: "المالديف" },
    { country: "Mali", country_ar: "مالي" },
    { country: "Malta", country_ar: "مالطا" },
    { country: "Mauritania", country_ar: "موريتانيا" },
    { country: "Mauritius", country_ar: "موريشيوس" },
    { country: "Mexico", country_ar: "المكسيك" },
    { country: "Moldova", country_ar: "مولدوفا" },
    { country: "Monaco", country_ar: "موناكو" },
    { country: "Mongolia", country_ar: "منغوليا" },
    { country: "Montenegro", country_ar: "الجبل الأسود" },
    { country: "Morocco", country_ar: "المغرب" },
    { country: "Mozambique", country_ar: "موزمبيق" },
    { country: "Myanmar", country_ar: "ميانمار" },
    { country: "Namibia", country_ar: "ناميبيا" },
    { country: "Nepal", country_ar: "نيبال" },
    { country: "Netherlands", country_ar: "هولندا" },
    { country: "New Zealand", country_ar: "نيوزيلندا" },
    { country: "Nicaragua", country_ar: "نيكاراغوا" },
    { country: "Niger", country_ar: "النيجر" },
    { country: "Nigeria", country_ar: "نيجيريا" },
    { country: "North Korea", country_ar: "كوريا الشمالية" },
    { country: "North Macedonia", country_ar: "مقدونيا الشمالية" },
    { country: "Norway", country_ar: "النرويج" },
    { country: "Oman", country_ar: "عمان" },
    { country: "Pakistan", country_ar: "باكستان" },
    { country: "Palestine", country_ar: "فلسطين" },
    { country: "Panama", country_ar: "بنما" },
    { country: "Papua New Guinea", country_ar: "بابوا غينيا الجديدة" },
    { country: "Paraguay", country_ar: "باراغواي" },
    { country: "Peru", country_ar: "بيرو" },
    { country: "Philippines", country_ar: "الفلبين" },
    { country: "Poland", country_ar: "بولندا" },
    { country: "Portugal", country_ar: "البرتغال" },
    { country: "Qatar", country_ar: "قطر" },
    { country: "Romania", country_ar: "رومانيا" },
    { country: "Russia", country_ar: "روسيا" },
    { country: "Rwanda", country_ar: "رواندا" },
    { country: "Saint Lucia", country_ar: "سانت لوسيا" },
    { country: "San Marino", country_ar: "سان مارينو" },
    { country: "Saudi Arabia", country_ar: "السعودية" },
    { country: "Senegal", country_ar: "السنغال" },
    { country: "Serbia", country_ar: "صربيا" },
    { country: "Seychelles", country_ar: "سيشيل" },
    { country: "Sierra Leone", country_ar: "سيراليون" },
    { country: "Singapore", country_ar: "سنغافورة" },
    { country: "Slovakia", country_ar: "سلوفاكيا" },
    { country: "Slovenia", country_ar: "سلوفينيا" },
    { country: "Somalia", country_ar: "الصومال" },
    { country: "South Africa", country_ar: "جنوب أفريقيا" },
    { country: "South Korea", country_ar: "كوريا الجنوبية" },
    { country: "South Sudan", country_ar: "جنوب السودان" },
    { country: "Spain", country_ar: "إسبانيا" },
    { country: "Sri Lanka", country_ar: "سريلانكا" },
    { country: "Sudan", country_ar: "السودان" },
    { country: "Suriname", country_ar: "سورينام" },
    { country: "Sweden", country_ar: "السويد" },
    { country: "Switzerland", country_ar: "سويسرا" },
    { country: "Syria", country_ar: "سوريا" },
    { country: "Tajikistan", country_ar: "طاجيكستان" },
    { country: "Tanzania", country_ar: "تنزانيا" },
    { country: "Thailand", country_ar: "تايلاند" },
    { country: "Togo", country_ar: "توغو" },
    { country: "Trinidad and Tobago", country_ar: "ترينيداد وتوباغو" },
    { country: "Tunisia", country_ar: "تونس" },
    { country: "Turkey", country_ar: "تركيا" },
    { country: "Turkmenistan", country_ar: "تركمانستان" },
    { country: "Uganda", country_ar: "أوغندا" },
    { country: "Ukraine", country_ar: "أوكرانيا" },
    { country: "United Arab Emirates", country_ar: "الإمارات" },
    { country: "United Kingdom", country_ar: "المملكة المتحدة" },
    { country: "United States", country_ar: "الولايات المتحدة" },
    { country: "Uruguay", country_ar: "أوروغواي" },
    { country: "Uzbekistan", country_ar: "أوزبكستان" },
    { country: "Vanuatu", country_ar: "فانواتو" },
    { country: "Venezuela", country_ar: "فنزويلا" },
    { country: "Vietnam", country_ar: "فيتنام" },
    { country: "Yemen", country_ar: "اليمن" },
    { country: "Zambia", country_ar: "زامبيا" },
    { country: "Zimbabwe", country_ar: "زيمبابوي" }
];